### ISSUE TITLE
SecurityError: Failed to execute 'showSaveFilePicker' on 'Window': Must be handling a user gesture to show a file picker.

### ISSUE THREAD

**Issue by LucaL1fe** [TesteurManiak/flutter_file_saver#17]
Hey, I get the error:
`SecurityError: Failed to execute 'showSaveFilePicker' on 'Window': Must be handling a user gesture to show a file picker.`
This error occurs from time to time. Any ideas how I can solve this problem would be great 😇

**Comment by TesteurManiak** [comment]
Does this happen when using the package on the web?
It might be an issue with the wrapper I've made to call the JS method `showSaveFilePicker`, I'm passing the `globalContext` from `dart:js_interop` library which maybe doesn't allow to call this method on certain condition, do you think you can provide a minimal reproducible example?

**Comment by LucaL1fe** [comment]
Yes happens on web. Unfortunatly I cant provide a code example, but I can say when the error occured. 

My Website ist literaly just a download button. Than start the debugger (press nothing). A new browser opens up with the application, if you now click the button the error occurs. (Both in Edge and in Chrome)

Maybe interesting if I press F12 before clicking the button (opening the inspector) it does work fine.

So the error is just in the fresh brwoser windows which gets opened from flutter debugger.

**Comment by TesteurManiak** [comment]
@LucaL1fe can you point to the linked branch (or its latest commit) and tell me if this works better for you:
```yaml
dependency_overrides:
  flutter_file_manager_web:
    git:
      url: https://github.com/TesteurManiak/flutter_file_saver.git
      ref: b586df4d2fc70bc2b5a08629f2926682884fe8c1
```
